# Configuration: https://www.masterclass.org/server/all-config
# Logging: https://www.masterclass.org/server/logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-parameters
data:
  # Clustering parameters
  KC_CACHE_STACK: "kubernetes"
  JAVA_OPTS_APPEND: "-Djgroups.dns.query=masterclass-jgroups.masterclass.svc"
  CACHE_OWNERS_COUNT: "3"
  CACHE_OWNERS_AUTH_SESSIONS_COUNT: "3"

  # Networking parameters
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME: "auth.cikume.com"
  KC_HOSTNAME_STRICT: "false"
  KC_PROXY: "edge"
  PROXY_ADDRESS_FORWARDING: "true"
  masterclass_HTTP_RELATIVE_PATH: "/"
  masterclass_ENABLE_HTTPS: 'false'
  KC_HOSTNAME_STRICT_HTTPS: 'false'
  masterclass_PROXY: "true"

  # Database parameters
  KC_DB: "postgres"
  KC_DB_URL_HOST: "postgresql-1730480228.masterclass.svc.cluster.local"
  # KC_DB_URL: "jdbc:postgresql://elecate-dev-postgresql.postgres.database.azure.com:5432/masterclass_dev2?sslmode=require&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory"
  # KC_DB_URL: "jdbc:postgresql://elecate-dev-postgresql.postgres.database.azure.com:5432/masterclass_dev2?sslmode=require&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory&tcpKeepAlive=true&connectTimeout=10&socketTimeout=30"
  KC_DB_URL: "jdbc:postgresql://postgresql-1730480228.masterclass.svc.cluster.local:5432/masterclass_db"
  # KC_DB_URL: "jdbc:postgresql://elecate-dev-postgresql.postgres.database.azure.com:5432/masterclass_dev2?sslmode=require"
  masterclass_DATABASE_HOST: "postgresql-1730480228.masterclass.svc.cluster.local"
  KC_DB_URL_PORT: "5432"
  masterclass_DATABASE_PORT: "5432"
  KC_DB_URL_DATABASE: "masterclass_db"
  masterclass_DATABASE_NAME: "masterclass_db"

  # Monitoring parameters
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_LOG: "console"
  KC_LOG_CONSOLE_OUTPUT: "json"
  KC_LOG_LEVEL: "info"

