apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.suffix }}
type: Opaque
data:
  HASURA_GRAPHQL_DATABASE_URL: {{ .Values.database.postgresUrl | b64enc }}
  HASURA_GRAPHQL_ADMIN_SECRET: {{ .Values.adminSecret | b64enc }}

# HASURA_GRAPHQL_METADATA_DATABASE_URL: {{ .Values.database.postgresUrl | b64enc }}